version: "3.7"

services:

  #link: localhost:8280/auth
  keycloak_microservices:
    container_name: keycloak_microservices
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - 8280:8080
    networks:
      - spring-security-network    
        
  #DataBase Security Student
  postgres_database_student:
    container_name: postgres_database_student
    image: postgres:${DATABASE_POSTGRES_STUDENT_VERSION}
    environment:
      DATABASE_HOST: ${DATABASE_POSTGRES_STUDENT_HOST}
      POSTGRES_DB: database_student
      POSTGRES_USER: ${DATABASE_POSTGRES_STUDENT_USER}
      POSTGRES_PASSWORD: ${DATABASE_POSTGRES_STUDENT_PASSWORD}
    volumes:
      - ./db/student/postgres-data:/var/lib/postgresql/data
      - ./db/student/postgres-init/sh_sql_dmp_files:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    restart: unless-stopped      
    networks:
      - spring-security-network
      
  #DataBase Security Professor
  postgres_database_professor:
    container_name: postgres_database_professor
    image: postgres:${DATABASE_POSTGRES_PROFESSOR_VERSION}
    environment:
      DATABASE_HOST: ${DATABASE_POSTGRES_PROFESSOR_HOST}
      POSTGRES_DB: database_professor
      POSTGRES_USER: ${DATABASE_POSTGRES_PROFESSOR_USER}
      POSTGRES_PASSWORD: ${DATABASE_POSTGRES_PROFESSOR_PASSWORD}
    volumes:
      - ./db/professor/postgres-data:/var/lib/postgresql/data
      - ./db/professor/postgres-init/sh_sql_dmp_files:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    restart: unless-stopped      
    networks:
      - spring-security-network

networks:
  spring-security-network:
    driver: bridge
      
      
      

  
  
  