version: "3.7"

services:

  #link: localhost:8280/auth
  keycloak_microservices:
    container_name: keycloak_microservices
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - 8280:8080
    networks:
      - spring-security-network    
        
  #DataBase Security
  postgres_security_database:
    container_name: postgres_security_database
    image: postgres:${SECURITY_DATABASE_POSTGRES_VERSION}
    environment:
      DATABASE_HOST: ${SECURITY_DATABASE_POSTGRES_HOST}
      POSTGRES_DB: security_database
      POSTGRES_USER: ${SECURITY_DATABASE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SECURITY_DATABASE_POSTGRES_PASSWORD}
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
      - ./db/postgres-init/sh_sql_dmp_files:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    restart: unless-stopped      
    networks:
      - spring-security-network

networks:
  spring-security-network:
    driver: bridge
      
      
      

  
  
  